// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package access

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AcessServiceClient is the client API for AcessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AcessServiceClient interface {
	FileAccessCtx(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessData, error)
}

type acessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAcessServiceClient(cc grpc.ClientConnInterface) AcessServiceClient {
	return &acessServiceClient{cc}
}

func (c *acessServiceClient) FileAccessCtx(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessData, error) {
	out := new(AccessData)
	err := c.cc.Invoke(ctx, "/access.AcessService/FileAccessCtx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcessServiceServer is the server API for AcessService service.
// All implementations must embed UnimplementedAcessServiceServer
// for forward compatibility
type AcessServiceServer interface {
	FileAccessCtx(context.Context, *AccessRequest) (*AccessData, error)
	mustEmbedUnimplementedAcessServiceServer()
}

// UnimplementedAcessServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAcessServiceServer struct {
}

func (UnimplementedAcessServiceServer) FileAccessCtx(context.Context, *AccessRequest) (*AccessData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileAccessCtx not implemented")
}
func (UnimplementedAcessServiceServer) mustEmbedUnimplementedAcessServiceServer() {}

// UnsafeAcessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AcessServiceServer will
// result in compilation errors.
type UnsafeAcessServiceServer interface {
	mustEmbedUnimplementedAcessServiceServer()
}

func RegisterAcessServiceServer(s *grpc.Server, srv AcessServiceServer) {
	s.RegisterService(&_AcessService_serviceDesc, srv)
}

func _AcessService_FileAccessCtx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcessServiceServer).FileAccessCtx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access.AcessService/FileAccessCtx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcessServiceServer).FileAccessCtx(ctx, req.(*AccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AcessService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "access.AcessService",
	HandlerType: (*AcessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FileAccessCtx",
			Handler:    _AcessService_FileAccessCtx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "access.proto",
}
